version: "3.9"
services:
  db:
    image: mysql:5.7
    
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '32000:3306'
    
      # Where our data will be persisted
    command: --init-file /data/application/init.sql
    volumes:
        - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_DATABASE: 'smarttbot'
      MYSQL_USER: 'nayara'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'
    healthcheck:
      test: "/usr/bin/mysql --user=nayara --password=123456 --execute \"SHOW DATABASES;\""
      timeout: 10s
      interval: 10s
      retries: 5
    networks: 
      - default
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      WAIT_HOSTS: mysql:32000
    depends_on:
      db:
        condition: service_healthy
          
    
  